#!/usr/bin/env python
"""Generate the agent-facing index: AGENTS.md (human+machine manifest, repo root) and
data/<cc>/index.json (flat machine index). Tier A of "plug into any agent".

Usage: python pipeline/build_index.py --country be   (or no --country to index all)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from common import (WIKI, REPO, read_note, write_if_changed, write_json,
                    country_dir, load_country, today)


def index_country(cc: str) -> list[dict]:
    rows = []
    root = WIKI / cc
    if not root.is_dir():
        return rows
    for md in sorted(root.rglob("*.md")):
        meta, _ = read_note(md)
        if not meta:
            continue
        rows.append({
            "country": cc,
            "type": meta.get("type"),
            "title": md.stem,
            "branch": meta.get("branch"),
            "insurer": (meta.get("insurer_slug") or meta.get("insurer")),
            "status": meta.get("status"),
            "path": str(md.relative_to(REPO)),
            "source_url": meta.get("source_url"),
            "freshness": meta.get("freshness"),
        })
    return rows


def countries_present() -> list[str]:
    # A country is a wiki/<cc>/ dir that has a matching sources/<cc>/_country.yml.
    # This skips editor dirs like .obsidian and any stray folders.
    from common import SOURCES
    if not WIKI.is_dir():
        return []
    out = []
    for d in WIKI.iterdir():
        if d.is_dir() and not d.name.startswith((".", "_")) \
                and (SOURCES / d.name / "_country.yml").is_file():
            out.append(d.name)
    return sorted(out)


def counts(rows: list[dict]) -> dict:
    c = {}
    for r in rows:
        c[r["type"]] = c.get(r["type"], 0) + 1
    return c


def render_agents_md(all_rows: list[dict], per_country: dict[str, list[dict]]) -> str:
    # header dated from the DATA (newest page freshness), not the clock, so a
    # rebuild without new data is a byte-identical no-op (the CI idempotence gate)
    newest = max((str(r.get("freshness") or "") for r in all_rows), default="") or today()
    L = [f"# AGENTS.md - machine index (data freshness: {newest})\n",
         "This file is generated by `pipeline/build_index.py`. It indexes the wiki so any agent can",
         "navigate it without guessing. Do not edit by hand.\n",
         "## Rules for agents\n",
         "- **Information only - no advice, no ranking.** Neutral facts and comparisons.",
         "- **Never edit `generated: true` pages** (products/insurers). Fix the JSON in "
         "`data/<cc>/extracted/` and rebuild.",
         "- **Every product fact traces to `source_url` + page.** No source, no claim.",
         "- **Respect `freshness`/`edition_date`.** Flag stale rather than hide.\n",
         "## Note types\n",
         "| type | folder | origin |",
         "|---|---|---|",
         "| branch | `wiki/<cc>/branches/` | hand-authored |",
         "| product | `wiki/<cc>/products/<insurer>/` | generated |",
         "| insurer | `wiki/<cc>/insurers/` | generated |",
         "| concept | `_meta/universal-glossary/`, `wiki/<cc>/glossary/` | hand-authored |",
         "| regulation | `wiki/<cc>/regulations/` | hand-authored |",
         "| moc | folder roots | hand + generated |\n",
         "## Coverage\n",
         "| country | branch | product | insurer | regulation | concept |",
         "|---|---|---|---|---|---|"]
    for cc, rows in sorted(per_country.items()):
        name = load_country(cc).get("name", cc)
        c = counts(rows)
        L.append(f"| {cc} ({name}) | {c.get('branch',0)} | {c.get('product',0)} | "
                 f"{c.get('insurer',0)} | {c.get('regulation',0)} | {c.get('concept',0)} |")
    L.append("\nMachine index per country: `data/<cc>/index.json`. Structured product data: "
             "`data/<cc>/extracted/`. Schema: `schema/`.\n")

    L.append("## Products index\n")
    L.append("| country | branch | insurer | title | freshness | source |")
    L.append("|---|---|---|---|---|---|")
    for r in sorted([r for r in all_rows if r["type"] == "product"],
                    key=lambda r: (r["country"], r.get("branch") or "", r.get("insurer") or "", r["title"])):
        src = f"[pdf]({r['source_url']})" if r.get("source_url") else ""
        L.append(f"| {r['country']} | {r.get('branch') or ''} | {r.get('insurer') or ''} | "
                 f"{r['title']} | {r.get('freshness') or ''} | {src} |")
    L.append("")
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--country")
    args = ap.parse_args()

    ccs = [args.country] if args.country else countries_present()
    per_country = {}
    all_rows = []
    for cc in ccs:
        rows = index_country(cc)
        per_country[cc] = rows
        all_rows.extend(rows)
        write_json(country_dir(cc) / "index.json", rows)
        print(f"[index] {cc}: {len(rows)} pages -> data/{cc}/index.json")

    # AGENTS.md is global - reindex every country present so counts stay correct.
    if args.country:
        for cc in countries_present():
            if cc not in per_country:
                per_country[cc] = index_country(cc)
                all_rows.extend(per_country[cc])

    wrote = write_if_changed(REPO / "AGENTS.md", render_agents_md(all_rows, per_country))
    print(f"[index] AGENTS.md {'updated' if wrote else 'unchanged'}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
